
package org.tmea.unido.ipmis.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MedicineWs", targetNamespace = "http://ws.ipmis.unido.tmea.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MedicineWs {


    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTestListString", targetNamespace = "http://ws.ipmis.unido.tmea.org/", className = "org.tmea.unido.ipmis.ws.GetTestListString")
    @ResponseWrapper(localName = "getTestListStringResponse", targetNamespace = "http://ws.ipmis.unido.tmea.org/", className = "org.tmea.unido.ipmis.ws.GetTestListStringResponse")
    @Action(input = "http://ws.ipmis.unido.tmea.org/MedicineWs/getTestListStringRequest", output = "http://ws.ipmis.unido.tmea.org/MedicineWs/getTestListStringResponse")
    public List<String> getTestListString();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTestString", targetNamespace = "http://ws.ipmis.unido.tmea.org/", className = "org.tmea.unido.ipmis.ws.GetTestString")
    @ResponseWrapper(localName = "getTestStringResponse", targetNamespace = "http://ws.ipmis.unido.tmea.org/", className = "org.tmea.unido.ipmis.ws.GetTestStringResponse")
    @Action(input = "http://ws.ipmis.unido.tmea.org/MedicineWs/getTestStringRequest", output = "http://ws.ipmis.unido.tmea.org/MedicineWs/getTestStringResponse")
    public String getTestString();

    /**
     * 
     * @return
     *     returns java.util.List<org.tmea.unido.ipmis.ws.Medicine>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllMedicine", targetNamespace = "http://ws.ipmis.unido.tmea.org/", className = "org.tmea.unido.ipmis.ws.GetAllMedicine")
    @ResponseWrapper(localName = "getAllMedicineResponse", targetNamespace = "http://ws.ipmis.unido.tmea.org/", className = "org.tmea.unido.ipmis.ws.GetAllMedicineResponse")
    @Action(input = "http://ws.ipmis.unido.tmea.org/MedicineWs/getAllMedicineRequest", output = "http://ws.ipmis.unido.tmea.org/MedicineWs/getAllMedicineResponse")
    public List<Medicine> getAllMedicine();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<org.tmea.unido.ipmis.ws.Medicine>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSearchResult", targetNamespace = "http://ws.ipmis.unido.tmea.org/", className = "org.tmea.unido.ipmis.ws.GetSearchResult")
    @ResponseWrapper(localName = "getSearchResultResponse", targetNamespace = "http://ws.ipmis.unido.tmea.org/", className = "org.tmea.unido.ipmis.ws.GetSearchResultResponse")
    @Action(input = "http://ws.ipmis.unido.tmea.org/MedicineWs/getSearchResultRequest", output = "http://ws.ipmis.unido.tmea.org/MedicineWs/getSearchResultResponse")
    public List<Medicine> getSearchResult(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
